# Import Pandas

To use the Pandas library, you need to import it into your coding environment. For these exercises, our coding environment is this Jupyter notebook. Pandas is typically imported and named as "pd".

In [21]:
# import the pandas library and use the alias 'pd'
import pandas as pd
import numpy as np
import seaborn as sns                       #visualisation
import matplotlib.pyplot as plt             #visualisation
%matplotlib inline     
sns.set(color_codes=True)

# Series

A series is a data type used by Pandas. It is like a one dimensional list, whose elements can be of any data type themselves.
Pandas contains a method, ``.Series()``, that initiates a series object from a Python list, tuple,

In [23]:
#create the s1 series from the list: [10,20,30,40,50]
my_list = [10, 20, 30, 40, 50]
s1 = pd.Series(my_list)

print(s1)
# additional practice
# create a series called s_tuple from the tuple: ("apple", "banana", "cherry")

my_tuple = ("apple", "banana", "cherry")
s_tuple = pd.Series(my_tuple)

print(s_tuple)

# create a series called s_dictionary from the dictionary: {"brand": "Ford", "model": "Mustang", "year": 1964}

my_dict = {"brand": "Ford", "model": "Mustang", "year": 1964}
s_dictionary = pd.Series(my_dict)

print(s_dictionary)

0    10
1    20
2    30
3    40
4    50
dtype: int64
0     apple
1    banana
2    cherry
dtype: object
brand       Ford
model    Mustang
year        1964
dtype: object

In [5]:
# fill in the blank with the series values and index values
import pandas as pd

s1 = pd.Series([10, 20, 30, 40, 50], index=['0', '1', '2', '3', '4'])
print("The s1 series values are:",s1.values),
print("The s1 index values are:", s1.index.values),
print("\n")

my_tuple = ("apple", "banana", "cherry")
s_tuple = pd.Series(my_tuple)
print("The s_tuple series values are:", s_tuple.values)
print("The s_tuple index values are:", s_tuple.index)
print("\n")

my_dict = {"brand": "Ford", "model": "Mustang", "year": 1964}
s_dictionary = pd.Series(my_dict)
print("The s_dictionary series values are:", s_dictionary.values)
print("The s_dictionary index values are:", s_dictionary.index)

The s1 series values are: [10 20 30 40 50]
The s1 index values are: ['0' '1' '2' '3' '4']


The s_tuple series values are: ['apple' 'banana' 'cherry']
The s_tuple index values are: RangeIndex(start=0, stop=3, step=1)


The s_dictionary series values are: ['Ford' 'Mustang' 1964]
The s_dictionary index values are: Index(['brand', 'model', 'year'], dtype='object')

Index values in a series are generated by default. We can also define custom indexes at the time of creating series.

Below is a series of marks (grades) and the associated subjects can be defined as custom row indexes.

In [14]:
# create the s2 series from the list [80,93,78,85,97] and with labeled indexes ['English','Science','Social','Tamil','Maths']
list = [80, 93, 78, 85, 97]
s2 = pd.Series(list)

import pandas as pd

values = [80, 93, 78, 85, 97]
s2 = pd.Series(values, index=['English', 'Science', 'Social', 'Tamil', 'Maths'])

In [15]:
# print the s2 series

print(s2)
print(s2['English'])

English    80
Science    93
Social     78
Tamil      85
Maths      97
dtype: int64
80

We can provide a name for the whole series, as well as a name for the indexes.

In [19]:
# assign the s2 series name to be "Student Marks"

import pandas as pd

values = [80, 93, 78, 85, 97]
s2 = pd.Series(values, index=['English', 'Science', 'Social', 'Tamil', 'Maths'])
s2.name = "Student Marks"

# assign the s2 index name to be "Subject"
s2.index.name = "Subject"

In [17]:
# print the s2 series again to see the newly assigned name and index name
print(s2)

Student Marks

## Subsetting the Series

Values inside the series can be accessed using the ``[ ]`` square bracket slicing operation

- Series can be sliced using the default index
- Series can also be sliced using string indices (indexes)

In [22]:
# return the first element in the s2 series

import pandas as pd


values = [97]
s2 = pd.Series(values, index=['English'])
print(s2)

English    97
dtype: int64

In [23]:
# slicing using default integer index

import pandas as pd

s = pd.Series([10, 20, 30, 40, 50])
s_slice = s[1:4]
print(s_slice)


# return the elements starting at position one and ending with the element at index 3

1    20
2    30
3    40
dtype: int64

In [25]:
# Slicing using string index

import pandas as pd

s = pd.Series([10, 20, 30, 40, 50], index=['a', 'b', 'c', 'd', 'e'])
s_slice = s['b':'d']
print(s_slice)



# return the element associated with the index 'Tamil'

s = pd.Series([80, 93, 78, 85, 97], index=['English', 'Science', 'Social', 'Tamil', 'Maths'])
tamil_score = s['Tamil']
print(tamil_score)

b    20
c    30
d    40
dtype: int64
85

## Creating a Series from a Dictionary

- A Python dictionary is a data structure which maps keys to a set of values.
- A dictionary contains key-value pairs.
- A series is similar to a dictionary in a way that it maps given indexes to a set of values.

Let's see how to create a series from a dictionary

I have a dictionary that represents fruits and prices. Let's create a series from this dictionary

In [26]:
# create a dictionary of fruit names and their prices. Use the values from the article

fruit_prices = {
    'apple': 0.6,
    'banana': 0.25,
    'orange': 0.7,
    'pear': 0.55,
    'pineapple': 2.5
}

In [30]:
# Lets convert this dictionary into a series
# use the pandas method .Series() 

fruit_series = pd.Series(values, index=[fruit_prices])

In [31]:
# print the series
print(fruit_series)

{'apple': 0.6, 'banana': 0.25, 'orange': 0.7, 'pear': 0.55, 'pineapple': 2.5}    97
dtype: int64

In [33]:
# Slice the series and retrieve price of grapes
import pandas as pd

fruit_prices = {
    'apple': 0.6,
    'banana': 0.25,
    'orange': 0.7,
    'pear': 0.55,
    'pineapple': 2.5
}


fruit_prices['grapes'] = 1.1
fruit_series = pd.Series(fruit_prices)
grapes_price = fruit_series['grapes']
print(grapes_price)

1.1

# DataFrame

## Create a DataFrame from a Series object

Let's create a DataFrame from the marks series we created in the above step.

In [35]:
# create a dataframe from the s2 series

import pandas as pd

# create the s2 series
s2 = pd.Series([80, 93, 78, 85, 97], index=['English', 'Science', 'Social', 'Tamil', 'Maths'])

# create a DataFrame from the s2 series
df = pd.DataFrame(s2, columns=['Marks'])

In [36]:
# print the dataframe

print(df)

         Marks
English     80
Science     93
Social      78
Tamil       85
Maths       97

## Create a DataFrame from a Dictionary

Let's say we have 2 series of heights and weights of the same set of persons and we want to put it together in a table.

Here we can create dictionary using both series and create a DataFrame using the Pandas ``.DataFrame()`` method.

In [ ]:
# Create height series using [5.3, 6.2,5.8,5.0,5.5] for values, ['Person 1','Person 2','Person 3','Person 4','Person 5'] for indexes

import pandas as pd

# create the height and weight series
heights = pd.Series([5.3, 6.2, 5.8, 5.0, 5.5], index=['Person 1', 'Person 2', 'Person 3', 'Person 4', 'Person 5'])
weights = pd.Series([130, 170, 150, 110, 140], index=['Person 1', 'Person 2', 'Person 3', 'Person 4', 'Person 5'])

# create a dictionary from the series
data = {'Height': heights, 'Weight': weights}

# create a DataFrame from the dictionary
df = pd.DataFrame(data)




# Create weight series (in kgs) using [65,89,75,60,59] for values and the same indexes as height

In [37]:
# Create a dataframe from the height and weight series above


print(df)

         Marks
English     80
Science     93
Social      78
Tamil       85
Maths       97